
enum Emoji: String, CaseIterable, Codable {
    case smilingFace = "🙂"
    case heartEyesCat = "😻"
    case hibiscus = "🌺"
    case dogFace = "🐶"
    case redHeart = "❤️"
    case screamingFace = "😱"
    case smilingFaceWithHalo = "😇"
    case angryFace = "😡"
    case coldFace = "🥶"
    case thinkingFace = "🤔"
    case raisingHands = "🙌"
    case hamburger = "🍔"
    case broccoli = "🥦"
    case pingPong = "🏓"
    case firstPlaceMedal = "🥇"
    case guitar = "🎸"
    case desertIsland = "🏝"
    case sleepyFace = "😪"
}
